### ISSUE TITLE
Add to daattali/addinslist

### ISSUE THREAD

**Issue by gadenbuie** [dreamRs/prefixer#1]
Just found this addin thanks to &commat;batpigandme on Twitter, super cool!

Would you consider adding it to the [addinslist](https://github.com/daattali/addinslist) for easier discovery and installation? I'd be happy to submit the PR on your behalf if you'd like.

**Comment by pvictor** [comment]
Hi!
Thanks! Yes I have to do that! Thanks for offering to do it, but I have other addins to add, I don't want to bother you with that. I let you know when it's done.

Victor

**Comment by pvictor** [comment]
Done! PR [#89](https://github.com/daattali/addinslist/pull/89)
